name: Build lume-epics

on:
  push:
    branches:
      - reg-test-setup
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    name: Python ${{ matrix.python-version }}, ${{ matrix.os }} build
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        uses: actions/setup-python@v2
        with:
          python-version: '${{ matrix.python-version }}'
      - run: |
          yes | pip install -r requirements.txt
          yes | pip install -r test-requirements.txt
          pip install -e .
          pytest


          
